name: project_view
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_smart_dialog: ^4.9.6+1
  get: ^4.6.5
  get_storage: ^2.1.1
  intl: ^0.18.1
  logger: ^2.0.1
  path: ^1.8.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
